#!/usr/bin/env ansible-playbook
- hosts: localhost
  vars_files:
    - defaults/main.yml
    - vars/main.yml

  roles:
    - role: geerlingguy.mysql
      mysql_databases:
        - name: "{{ dbname }}"
          encoding: utf8mb4
          collation: utf8mb4_unicode_ci
      mysql_users:
        - name: "{{ dbuser }}"
          host: "%"
          password: "{{ dbpassword }}"
          priv: "{{ dbname }}.*:ALL"

    - role: jimmy01240397.nodejs 

  tasks:
    - name: include main task
      include: tasks/main.yml
  
  handlers:
    - include: handlers/main.yml
